create table if not exists public.vintpop_listings (
  id text primary key,
  url text not null,
  title text not null,
  description text,
  price numeric(10,2) not null check (price >= 0),
  currency text not null default 'EUR',
  image_url text,
  images jsonb not null default '[]'::jsonb,
  location_city text,
  category_id integer,
  seller_id text,
  seller_name text,
  seller_type text,
  seller_badge text,
  seller_rating numeric,
  seller_review_count integer,
  seller_active_count integer,
  seller_furniture_count integer,
  seller_summary jsonb,
  matched_queries text[] not null default '{}',
  wallapop_created_at timestamptz,
  first_seen_at timestamptz not null default now(),
  last_analyzed_at timestamptz,
  jev_pre jsonb,
  google_vision jsonb,
  jev_final jsonb,
  pre_score numeric,
  visual_score numeric,
  candidate_score numeric,
  status text not null default 'pending' check (status in ('pending','hot','review','discarded','error')),
  error text
);

create table if not exists public.vintpop_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  fetched_count integer not null default 0,
  new_count integer not null default 0,
  analyzed_count integer not null default 0,
  google_calls integer not null default 0,
  hot_count integer not null default 0,
  review_count integer not null default 0,
  errors jsonb not null default '[]'::jsonb
);

create index if not exists vintpop_listings_score_idx on public.vintpop_listings (candidate_score desc nulls last, first_seen_at desc);
create index if not exists vintpop_listings_status_idx on public.vintpop_listings (status, first_seen_at desc);
create index if not exists vintpop_listings_seller_idx on public.vintpop_listings (seller_id);

alter table public.vintpop_listings enable row level security;
alter table public.vintpop_runs enable row level security;

grant select on public.vintpop_listings to anon, authenticated;
grant select on public.vintpop_runs to anon, authenticated;

create policy "vintpop public read listings" on public.vintpop_listings for select to anon, authenticated using (true);
create policy "vintpop public read runs" on public.vintpop_runs for select to anon, authenticated using (true);
